name: Deploy project to GCP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions: write-all

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Auth with google
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          service_account: 'github-trevorism-gcloud@trevorism-gcloud.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/159773244195/locations/global/workloadIdentityPools/github-trevorism-gcloud-pool/providers/trevorism-gcloud-provider'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build appengineStage

      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0.8.0'
        with:
          working_directory: "build/staged-app"
          deliverables: 'app.yaml'
          promote: true
          version: '0-2-0'
