name: Deploy project to GCP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/deploy.yml@master
    if: success() || failure()
    needs: [call-build]
    with:
      gcp_project: 'trevorism-gcloud'
      gcp_project_id: '159773244195'
      version: '0-1-2'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
